FROM rstudio:4.0.0

USER rstudio

# install and configure doom-emacs
RUN git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d \
    && yes | ~/.emacs.d/bin/doom install \
    && mv ~/.doom.d ~/.doom.d.org \
    && git clone https://github.com/MarselScheer/.doom.d.git ~/.doom.d \
    && ~/.emacs.d/bin/doom sync

# root at the end is need, otherwise
# container stops directly after start?!?
USER root
